import turtle 
f = turtle.Turtle()
f.speed(30)
def rr():
	l= turtle.Turtle()
	l.color("black")
	l.begin_fill()
	l.goto(68,-80)
	l.pensize(20)
	l.fd(50)
	l.rt(110)
	l.fd (100)
	l.lt(110)
	l.fd(50)
	l.hideturtle()		
rr()	
def gg():
	 f.begin_fill()
	 f.color("black")
	 f.pensize(3)
	 f.circle(100,360,1000)
	 f.end_fill()
	 f.hideturtle()
def hh():
 hhk = turtle.Turtle()
 hhk.speed(20)
 hhk.penup()
 hhk.goto(-2,76)
 hhk.color("black")
 hhk.pensize(8)
 hhk.begin_fill()
 hhk.circle(25,360,1001)
 hhk.end_fill()
 hhk.hideturtle() 
def df () :
	 fd = turtle.Turtle()
	 fd.color("red")
	 fd.begin_fill()
	 fd.goto(68,160)
	 fd.pensize(4)
	 for i in range (9):
	 	fd.lt(-100)
	 	fd.circle (-180,60)
	 fd.end_fill()
	 fd.hideturtle()
def mf () :
	 fd = turtle.Turtle()
	 #blue
	 fd.color("black")
	 fd.goto(68,160)
	 fd.pensize(5)
	 for i in range (9):
		 fd.lt(-100)
		 fd.circle (-180,60)
	 fd.hideturtle()
def yers():
 g = turtle.Turtle()
 g.color('grey')
 g.penup()
 g.begin_fill()
 g.goto(-230,99)
 g.rt(50)
 
 g.circle(300,100)
 g.lt(80)
 g.circle(300,100)
 g.end_fill()
 g.hideturtle()
def dd():
 oo = turtle.Turtle()
 oo.goto(-230,99)
 oo.pensize(40) 
 oo.rt(50)
 oo.circle(300,100)
 oo.lt(80)
 oo.circle(300,100)
 oo.hideturtle()
dd()
yers()
gg()
df()
mf()
hh()
turtle.done()